### ISSUE TITLE
Wrong region for some places

### ISSUE THREAD

**Issue by jannomeister** [hyubs/ncovph#20]
Hello, when I tried the `/confirmed-cases` api and group them into regions, there were patients from Iligan City that is being grouped to REGION_XII, I believe Iligan City is still part of Region X.

**Comment by hubertursua** [comment]
Noting this. No ETA yet for this.

The mapping happens in the sequence of city → province → region

I verified that Iligan City belongs to Region X. However it's mapped as Region XII because it is listed under Lanao del Norte which belongs to Region XII. Lanao del Norte used to be Region X but was moved to Region XII.

There are no exceptions to independent cities (a.k.a cities with no province), thus they are mapped to their geographic provinces.

I have solutions in mind but I need to weigh which one of the changes will make the least impact on the other users of the API.

**Comment by jannomeister** [comment]
@hyubs thanks! and also your project is so awesome :)

**Comment by jannomeister** [comment]
I think Lanao del norte is still part of Region X. All the data from google points to Region X as the region of lanao del norte

**Comment by hubertursua** [comment]
Closing this issue for the following reasons:

1. v1 of the API is already deprecated and unsupported.
2. Location data in v2 now uses PSGC standard, which addresses the issue (3527e041457ccc6da0951d975c8b81aa0971a184).
